language: ruby

rvm:
  - ruby-head
  - 2.0.0
  - 1.9.3
  - rbx
  - jruby-head
  - jruby-19mode

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx
    - rvm: jruby-head
    - rvm: jruby-19mode

before_install:
  - gem install bundler